<a href="https://colab.research.google.com/github/shivani789/Complete_practical_files/blob/main/hebb_learning_character_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
#correct code using 3*3 
#tested on 4 examples 
import numpy as np 

c = np.array([
              1, 1, 1,
              1, -1, -1,
              1, 1, 1
])
o = np.array([
              1, 1, 1,
              1, -1, 1,
              1, 1, 1
])
inputs = np.append([np.append(c, 1)], [np.append(o, 1)], axis=0)
print(inputs)

[[ 1  1  1  1 -1 -1  1  1  1  1]
 [ 1  1  1  1 -1  1  1  1  1  1]]


In [23]:
y = np.array([1, -1])
print(y) 

[ 1 -1]


In [24]:
weights = np.zeros((10,), dtype = int)

def print_weights(weights):
  for i in range(9):
    print("W%d = %d" %(i+1, weights[i]))
  print("B = %d" %(weights[9]))

print_weights(weights)

W1 = 0
W2 = 0
W3 = 0
W4 = 0
W5 = 0
W6 = 0
W7 = 0
W8 = 0
W9 = 0
B = 0


In [25]:
for i in range(len(y)):
  for j in range(len(weights)):
    weights[j] = weights[j] + y[i]*inputs[i][j]
  print("After Epoch %d, the weights are:" %(i+1))
  print_weights(weights)

After Epoch 1, the weights are:
W1 = 1
W2 = 1
W3 = 1
W4 = 1
W5 = -1
W6 = -1
W7 = 1
W8 = 1
W9 = 1
B = 1
After Epoch 2, the weights are:
W1 = 0
W2 = 0
W3 = 0
W4 = 0
W5 = 0
W6 = -2
W7 = 0
W8 = 0
W9 = 0
B = 0


In [26]:
result=[]
for i in range(len(y)):
  ans=0
  for j in range(len(weights)):
    ans += y[i]*inputs[i][j]
  result.append(ans)

print("The final weights are:")
print_weights(weights)

#the actual output matches the target output 
#for character c, output is positive and for o output is negative 
print("summation of product of xi and wi:")
print(result)

The final weights are:
W1 = 0
W2 = 0
W3 = 0
W4 = 0
W5 = 0
W6 = -2
W7 = 0
W8 = 0
W9 = 0
B = 0
summation of product of xi and wi:
[6, -8]


In [35]:
#checking other inputs 
check1 = np.array([
              1, 1, 1,
              1, 1, 1,
              1, 1, 1
])

check2 = np.array([
              1, 1, 1,
              -1, -1, 1,
              1, 1, 1
])

inputs2 = np.append([np.append(check1, 1)], [np.append(c, 1)], axis=0)
inputs3 = np.append([np.append(check1, 1)], [np.append(check2, 1)], axis=0)

print(inputs2)
print("\n")
print(inputs3)

[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1 -1 -1  1  1  1  1]]


[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1 -1 -1  1  1  1  1  1]]


In [28]:
y = np.array([1, -1])
print(y) 

[ 1 -1]


In [29]:
weights2 = np.zeros((10,), dtype = int)

def print_weights(weights2):
  for i in range(9):
    print("W%d = %d" %(i+1, weights2[i]))
  print("B = %d" %(weights2[9]))

print_weights(weights2)

W1 = 0
W2 = 0
W3 = 0
W4 = 0
W5 = 0
W6 = 0
W7 = 0
W8 = 0
W9 = 0
B = 0


In [36]:
weights3 = np.zeros((10,), dtype = int)

def print_weights(weights3):
  for i in range(9):
    print("W%d = %d" %(i+1, weights3[i]))
  print("B = %d" %(weights3[9]))

print_weights(weights3)

W1 = 0
W2 = 0
W3 = 0
W4 = 0
W5 = 0
W6 = 0
W7 = 0
W8 = 0
W9 = 0
B = 0


In [30]:
for i in range(len(y)):
  for j in range(len(weights2)):
    weights2[j] = weights2[j] + y[i]*inputs2[i][j]
  print("After Epoch %d, the weights are:" %(i+1))
  print_weights(weights2)

After Epoch 1, the weights are:
W1 = 1
W2 = 1
W3 = 1
W4 = 1
W5 = 1
W6 = 1
W7 = 1
W8 = 1
W9 = 1
B = 1
After Epoch 2, the weights are:
W1 = 0
W2 = 0
W3 = 0
W4 = 0
W5 = 2
W6 = 2
W7 = 0
W8 = 0
W9 = 0
B = 0


In [47]:
result2=[]
for i in range(len(y)):
  ans2=0
  for j in range(len(weights2)):
    ans2 += y[i]*inputs2[i][j]
  result2.append(ans2)

print("The final weights are:")
print_weights(weights2)

#the actual output matches the target output 
#for character c, output is positive and for o output is negative 
print("summation of product of xi and wi:")
print(result2)

The final weights are:
W1 = 0
W2 = 0
W3 = 0
W4 = 0
W5 = 2
W6 = 2
W7 = 0
W8 = 0
W9 = 0
B = 0
summation of product of xi and wi:
[10, -6]


In [37]:
for i in range(len(y)):
  for j in range(len(weights3)):
    weights3[j] = weights3[j] + y[i]*inputs3[i][j]
  print("After Epoch %d, the weights are:" %(i+1))
  print_weights(weights3)

After Epoch 1, the weights are:
W1 = 1
W2 = 1
W3 = 1
W4 = 1
W5 = 1
W6 = 1
W7 = 1
W8 = 1
W9 = 1
B = 1
After Epoch 2, the weights are:
W1 = 0
W2 = 0
W3 = 0
W4 = 2
W5 = 2
W6 = 0
W7 = 0
W8 = 0
W9 = 0
B = 0


In [46]:
result3=[]
for i in range(len(y)):
  ans3=0
  for j in range(len(weights3)):
    ans3 += y[i]*inputs3[i][j]
  result3.append(ans3)

print("The final weights are:")
print_weights(weights3)

#the actual output matches the target output 
#for character c, output is positive and for o output is negative 
print("summation of product of xi and wi:")
print(result3)

The final weights are:
W1 = 0
W2 = 0
W3 = 0
W4 = 2
W5 = 2
W6 = 0
W7 = 0
W8 = 0
W9 = 0
B = 0
summation of product of xi and wi:
[10, -6]


In [40]:
#testing on solved problem of sivanandam and deepa
import numpy as np 

l = np.array([
              1, -1, -1,
              1, -1, -1,
              1, 1, 1
])
u = np.array([
              1, -1, 1,
              1, -1, 1,
              1, 1, 1
])
inputs_solved = np.append([np.append(l, 1)], [np.append(u, 1)], axis=0)
print(inputs_solved)

[[ 1 -1 -1  1 -1 -1  1  1  1  1]
 [ 1 -1  1  1 -1  1  1  1  1  1]]


In [41]:
y = np.array([1, -1])
print(y) 

[ 1 -1]


In [42]:
weights_solved = np.zeros((10,), dtype = int)

def print_weights_solved(weights_solved):
  for i in range(9):
    print("W%d = %d" %(i+1, weights_solved[i]))
  print("B = %d" %(weights_solved[9]))

print_weights(weights_solved)

W1 = 0
W2 = 0
W3 = 0
W4 = 0
W5 = 0
W6 = 0
W7 = 0
W8 = 0
W9 = 0
B = 0


In [43]:
for i in range(len(y)):
  for j in range(len(weights_solved)):
    weights_solved[j] = weights_solved[j] + y[i]*inputs_solved[i][j]
  print("After Epoch %d, the weights are:" %(i+1))
  print_weights(weights_solved)

After Epoch 1, the weights are:
W1 = 1
W2 = -1
W3 = -1
W4 = 1
W5 = -1
W6 = -1
W7 = 1
W8 = 1
W9 = 1
B = 1
After Epoch 2, the weights are:
W1 = 0
W2 = 0
W3 = -2
W4 = 0
W5 = 0
W6 = -2
W7 = 0
W8 = 0
W9 = 0
B = 0


In [45]:
result_solved=[]
for i in range(len(y)):
  ans_solved=0
  for j in range(len(weights_solved)):
    ans_solved += y[i]*inputs_solved[i][j]
  result_solved.append(ans_solved)

print("The final weights are:")
print_weights(weights_solved)

#the actual output matches the target output 
#for character c, output is positive and for o output is negative 
print("summation of product of xi and wi:")
print(result_solved)

The final weights are:
W1 = 0
W2 = 0
W3 = -2
W4 = 0
W5 = 0
W6 = -2
W7 = 0
W8 = 0
W9 = 0
B = 0
summation of product of xi and wi:
[2, -6]
